// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sorcha.Blueprint.Service.Data;

#nullable disable

namespace Sorcha.Blueprint.Service.Data.Migrations
{
    [DbContext(typeof(BlueprintDbContext))]
    partial class BlueprintDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("blueprint")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.ActionEntity", b =>
                {
                    b.Property<string>("TransactionHash")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IdempotencyExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("RegisterAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionHash");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Actions_IdempotencyKey")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("WalletAddress", "RegisterAddress")
                        .HasDatabaseName("IX_Actions_Wallet_Register");

                    b.ToTable("Actions", "blueprint");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.BlueprintDraftAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "UserId")
                        .IsUnique();

                    b.ToTable("BlueprintDraftAccess", "blueprint");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.BlueprintDraftEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_Drafts_OrgId");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Drafts_OwnerId");

                    b.ToTable("BlueprintDrafts", "blueprint");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.BlueprintTemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Templates_Category");

                    b.ToTable("BlueprintTemplates", "blueprint");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.FileMetadataEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomMetadata")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransactionHash");

                    b.ToTable("FileMetadata", "blueprint");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.InstanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccumulatedData")
                        .HasColumnType("jsonb");

                    b.Property<string>("ActiveBranches")
                        .HasColumnType("jsonb");

                    b.Property<string>("BlueprintId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BlueprintVersion")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedActionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentActionIds")
                        .HasColumnType("jsonb");

                    b.Property<string>("FirstTransactionId")
                        .HasColumnType("text");

                    b.Property<bool>("IsReadOnlyMirror")
                        .HasColumnType("boolean");

                    b.Property<string>("LastTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ParticipantWallets")
                        .HasColumnType("jsonb");

                    b.Property<string>("PendingActionPayloads")
                        .HasColumnType("jsonb");

                    b.Property<string>("RegisterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId")
                        .HasDatabaseName("IX_Instances_BlueprintId");

                    b.HasIndex("RegisterId")
                        .HasDatabaseName("IX_Instances_RegisterId");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Instances_State");

                    b.ToTable("Instances", "blueprint");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.BlueprintDraftAccessEntity", b =>
                {
                    b.HasOne("Sorcha.Blueprint.Service.Data.Entities.BlueprintDraftEntity", "Draft")
                        .WithMany("AccessEntries")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.FileMetadataEntity", b =>
                {
                    b.HasOne("Sorcha.Blueprint.Service.Data.Entities.ActionEntity", "Action")
                        .WithMany("Files")
                        .HasForeignKey("TransactionHash")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.ActionEntity", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Sorcha.Blueprint.Service.Data.Entities.BlueprintDraftEntity", b =>
                {
                    b.Navigation("AccessEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
