// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sorcha Contributors

using Bunit;
using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;
using MudBlazor.Services;
using Sorcha.Blueprint.Models;
using Sorcha.UI.Core.Services.Designer;
using Sorcha.UI.Web.Client.Pages.DesignerShell.Stages;
using Xunit;
using BlueprintModel = Sorcha.Blueprint.Models.Blueprint;
using ActionModel = Sorcha.Blueprint.Models.Action;

namespace Sorcha.UI.Core.Tests.Components.Designer;

/// <summary>
/// Feature 142 US4 (T045 / FR-011) — the Describe stage canvas must reflect AI updates live as
/// the blueprint takes shape. The journey re-renders on every <see cref="DesignerContext.Changed"/>
/// event, which fires once per public mutation (incl. <see cref="DesignerContext.ApplyAiUpdate"/>).
/// </summary>
public class DescribeStageLiveJourneyTests : BunitContext
{
    public DescribeStageLiveJourneyTests()
    {
        Services.AddMudServices();
        Services.AddScoped<DesignerContext>();
        JSInterop.Mode = JSRuntimeMode.Loose;
    }

    [Fact]
    public void DescribeStage_StartsWithEmptyJourney_WhenNoBlueprintLoaded()
    {
        var cut = Render<DescribeStage>();

        cut.Find("[data-testid='stage-describe']").Should().NotBeNull();
        cut.FindAll("[data-testid^='journey-step-']").Should().BeEmpty(
            "no steps before a blueprint is applied");
    }

    [Fact]
    public void DescribeStage_ApplyAiUpdate_RendersJourneyLive()
    {
        var ctx = Services.GetRequiredService<DesignerContext>();
        var cut = Render<DescribeStage>();

        cut.FindAll("[data-testid^='journey-step-']").Should().BeEmpty();

        // Simulate the AiDesignerPane → DesignerContext.ApplyAiUpdate live channel.
        ctx.ApplyAiUpdate(MakeBlueprint(stepCount: 2), val: null, editedActionId: null);

        cut.FindAll("[data-testid^='journey-step-']").Should().HaveCount(2,
            "the Describe-stage journey must reflect an AI-driven blueprint update live (FR-011)");
    }

    [Fact]
    public void DescribeStage_SuccessiveAiUpdates_KeepJourneyInSync()
    {
        var ctx = Services.GetRequiredService<DesignerContext>();
        var cut = Render<DescribeStage>();

        ctx.ApplyAiUpdate(MakeBlueprint(stepCount: 1), val: null, editedActionId: null);
        cut.FindAll("[data-testid^='journey-step-']").Should().HaveCount(1);

        ctx.ApplyAiUpdate(MakeBlueprint(stepCount: 3), val: null, editedActionId: null);
        cut.FindAll("[data-testid^='journey-step-']").Should().HaveCount(3,
            "every successive AI update must re-render the journey");
    }

    private static BlueprintModel MakeBlueprint(int stepCount)
    {
        var bp = new BlueprintModel
        {
            Id = $"bp-live-{stepCount}",
            Title = "Live journey smoke",
            Description = "Generated by the DescribeStage live-render test.",
            Version = 1,
            Participants =
            [
                new Participant { Id = "applicant", Name = "Applicant" },
                new Participant { Id = "reviewer", Name = "Reviewer", WalletAddress = "ws11qreviewer" },
            ],
            Actions = [],
        };
        for (var i = 1; i <= stepCount; i++)
        {
            bp.Actions.Add(new ActionModel
            {
                Id = i,
                Title = $"Step {i}",
                Description = $"Step {i} body.",
                Sender = i % 2 == 1 ? "applicant" : "reviewer",
                IsStartingAction = i == 1,
            });
        }
        return bp;
    }
}
