// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sorcha Contributors

using System.Buffers.Text;
using System.Security.Cryptography;

namespace Sorcha.Tenant.Service.Data;

/// <summary>
/// Where a service principal's seeded client secret came from. Never used to decide
/// WHETHER to seed — only to log what happened, since the secret value itself must
/// never be logged (issue #1412).
/// </summary>
public enum ServicePrincipalSecretSource
{
    /// <summary>Read from <c>Seed:ServicePrincipals:{clientId}</c> — a per-deploy secret
    /// generated by <c>scripts/sorcha-setup.sh</c> into <c>.env</c>. Valid in every environment.</summary>
    Configured,

    /// <summary>No configured secret — a fresh random secret was generated. Only reachable
    /// outside Production/Staging (compose's <c>${VAR:?...}</c> guard means a real deployment
    /// always has the config; this path exists for unit/integration tests that seed without
    /// config, which are self-contained and need no cross-service agreement).
    /// Production/Staging refuse instead (see <see cref="ServicePrincipalSecretResolver.Resolve"/>).</summary>
    Generated
}

/// <summary>
/// Resolves the client secret to seed for a single service principal, given the per-deploy
/// configured value (if any), the committed dev-literal fallback, and the running environment.
/// Extracted from <see cref="DatabaseInitializer"/> so the selection logic is unit-testable
/// without a database (issue #1412).
/// </summary>
public static class ServicePrincipalSecretResolver
{
    /// <summary>
    /// Resolution order, per service principal:
    /// <list type="number">
    /// <item>A configured secret (<c>Seed:ServicePrincipals:{clientId}</c>) always wins — this is
    /// the per-deploy secret generated by the installer and injected into both the client env
    /// and this seed config, so client and server agree. Valid in every environment. In every
    /// real deployment this is always present: compose guards the matching client-side
    /// <c>ServiceAuth__ClientSecret</c>/seed vars with <c>${VAR:?...}</c>, so a bare
    /// `docker compose up` without a generated <c>.env</c> refuses to start at all.</item>
    /// <item>Production or Staging with no configured secret FAILS CLOSED. Seeding a random
    /// secret the client services can never learn is the exact silent-break bug this resolver
    /// exists to close — refusing loudly at startup is strictly better than a service that starts
    /// but can never authenticate to another.</item>
    /// <item>Any other environment (e.g. Testing) with no configured secret generates a fresh
    /// random secret — acceptable because nothing outside the test process needs to agree with it.</item>
    /// </list>
    /// </summary>
    /// <param name="clientId">The service principal's <c>ClientId</c> — used only for the
    /// fail-closed exception message and the configuration key shape.</param>
    /// <param name="configuredValue">The value read from <c>Seed:ServicePrincipals:{clientId}</c>,
    /// or null/empty/whitespace if absent.</param>
    /// <param name="environment">The running <c>ASPNETCORE_ENVIRONMENT</c> value (may be null).</param>
    /// <returns>The resolved secret plus where it came from.</returns>
    /// <exception cref="InvalidOperationException">Thrown when running as Production or Staging
    /// with no configured secret.</exception>
    public static (string ClientSecret, ServicePrincipalSecretSource Source) Resolve(
        string clientId,
        string? configuredValue,
        string? environment)
    {
        if (!string.IsNullOrWhiteSpace(configuredValue))
        {
            return (configuredValue, ServicePrincipalSecretSource.Configured);
        }

        if (IsEnvironment(environment, "Production") || IsEnvironment(environment, "Staging"))
        {
            throw new InvalidOperationException(
                $"No service-principal secret configured for '{clientId}'. Set " +
                $"Seed:ServicePrincipals:{clientId} (env Seed__ServicePrincipals__{clientId}). " +
                "Refusing to seed a random secret the client services cannot know.");
        }

        return (GenerateClientSecret(), ServicePrincipalSecretSource.Generated);
    }

    private static bool IsEnvironment(string? environment, string expected) =>
        string.Equals(environment, expected, StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Generates a cryptographically secure client secret.
    /// </summary>
    private static string GenerateClientSecret()
    {
        var bytes = RandomNumberGenerator.GetBytes(32);
        return Base64Url.EncodeToString(bytes);
    }
}
