<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sorcha.Verifier.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="QRCoder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Sorcha.CitizenWallet.Abstractions\Sorcha.CitizenWallet.Abstractions.csproj" />
    <ProjectReference Include="..\..\Common\Sorcha.ServiceClients.Http\Sorcha.ServiceClients.Http.csproj" />
    <ProjectReference Include="..\..\Common\Sorcha.ServiceDefaults\Sorcha.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Common\Sorcha.Verifier.Engine\Sorcha.Verifier.Engine.csproj" />
    <ProjectReference Include="..\Sorcha.UI\Sorcha.UI.Components.User\Sorcha.UI.Components.User.csproj" />
  </ItemGroup>

</Project>
