// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sorcha Contributors

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sorcha.Peer.Service.Data;

#nullable disable

namespace Sorcha.Peer.Service.Data.Migrations
{
    [DbContext(typeof(PeerDbContext))]
    [Migration("20260309100818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("peer")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sorcha.Peer.Service.Data.PeerNodeEntity", b =>
                {
                    b.Property<string>("PeerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AverageLatencyMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSeedNode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Protocols")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PeerId");

                    b.HasIndex("IsBanned")
                        .HasDatabaseName("IX_Peers_IsBanned");

                    b.HasIndex("IsSeedNode")
                        .HasDatabaseName("IX_Peers_IsSeedNode");

                    b.HasIndex("LastSeen")
                        .HasDatabaseName("IX_Peers_LastSeen");

                    b.ToTable("Peers", "peer");
                });

            modelBuilder.Entity("Sorcha.Peer.Service.Data.QueuedTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DataSize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GossipRound")
                        .HasColumnType("integer");

                    b.Property<bool>("HasFullData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("HopCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginPeerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RegisterId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TTL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3600);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TransactionData")
                        .HasColumnType("bytea");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EnqueuedAt")
                        .HasDatabaseName("IX_QueuedTransactions_EnqueuedAt");

                    b.HasIndex("RegisterId")
                        .HasDatabaseName("IX_QueuedTransactions_RegisterId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_QueuedTransactions_Status");

                    b.ToTable("queued_transactions", "peer");
                });

            modelBuilder.Entity("Sorcha.Peer.Service.Data.RegisterSubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSyncedDocketVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("LastSyncedTransactionVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("RegisterId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SourcePeerIds")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SyncState")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDocketsInChain")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId")
                        .IsUnique()
                        .HasDatabaseName("IX_RegisterSubscriptions_RegisterId");

                    b.HasIndex("SyncState")
                        .HasDatabaseName("IX_RegisterSubscriptions_SyncState");

                    b.ToTable("RegisterSubscriptions", "peer");
                });

            modelBuilder.Entity("Sorcha.Peer.Service.Data.SyncCheckpointEntity", b =>
                {
                    b.Property<string>("PeerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RegisterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("CurrentVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("LastSyncTime")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NextSyncDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourcePeerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.HasKey("PeerId", "RegisterId");

                    b.ToTable("SyncCheckpoints", "peer");
                });
#pragma warning restore 612, 618
        }
    }
}
