<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Sorcha.Register.Models</PackageId>
    <Description>Domain models for the distributed ledger register</Description>
    <PackageTags>sorcha;register;models;ledger</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/system-register-genesis.json" />
  </ItemGroup>

</Project>
